service_map <- list(
  'v201405'=
    c('ActivityGroupService', 'ActivityService', 'AdRuleService',
     'AudienceSegmentService', 'BaseRateService', 'CompanyService',
     'ContactService', 'ContentBundleService',
     'ContentMetadataKeyHierarchyService', 'ContentService',
     'CreativeService', 'CreativeSetService', 'CreativeTemplateService',
     'CreativeWrapperService', 'CustomFieldService',
     'CustomTargetingService', 'ExchangeRateService', 'ForecastService',
     'InventoryService', 'LabelService',
     'LineItemCreativeAssociationService', 'LineItemService',
     'LineItemTemplateService', 'LiveStreamEventService', 'NetworkService',
     'OrderService', 'PlacementService', 'ProductService',
     'ProductTemplateService', 'ProposalLineItemService', 'ProposalService',
     'PublisherQueryLanguageService', 'RateCardCustomizationService',
     'RateCardCustomizationGroupService', 'RateCardService',
     'ReconciliationOrderReportService', 'ReconciliationReportRowService',
     'ReconciliationReportService', 'ReportService',
     'SuggestedAdUnitService', 'TeamService', 'UserService',
     'UserTeamAssociationService', 'WorkflowRequestService'),
  'v201408'=
    c('ActivityGroupService', 'ActivityService', 'AdRuleService',
     'AudienceSegmentService', 'BaseRateService', 'CompanyService',
     'ContactService', 'ContentBundleService',
     'ContentMetadataKeyHierarchyService', 'ContentService',
     'CreativeService', 'CreativeSetService', 'CreativeTemplateService',
     'CreativeWrapperService', 'CustomFieldService',
     'CustomTargetingService', 'ExchangeRateService', 'ForecastService',
     'InventoryService', 'LabelService',
     'LineItemCreativeAssociationService', 'LineItemService',
     'LineItemTemplateService', 'LiveStreamEventService', 'NetworkService',
     'OrderService', 'PlacementService', 'PremiumRateService',
     'ProductService', 'ProductTemplateService', 'ProposalLineItemService',
     'ProposalService', 'PublisherQueryLanguageService', 'RateCardService',
     'ReconciliationOrderReportService', 'ReconciliationReportRowService',
     'ReconciliationReportService', 'ReportService',
     'SuggestedAdUnitService', 'TeamService', 'UserService',
     'UserTeamAssociationService', 'WorkflowRequestService'),
  'v201411'=
    c('ActivityGroupService', 'ActivityService', 'AdExclusionRuleService',
     'AdRuleService', 'AudienceSegmentService', 'BaseRateService',
     'CompanyService', 'ContactService', 'ContentBundleService',
     'ContentMetadataKeyHierarchyService', 'ContentService',
     'CreativeService', 'CreativeSetService', 'CreativeTemplateService',
     'CreativeWrapperService', 'CustomFieldService',
     'CustomTargetingService', 'ExchangeRateService', 'ForecastService',
     'InventoryService', 'LabelService',
     'LineItemCreativeAssociationService', 'LineItemService',
     'LineItemTemplateService', 'LiveStreamEventService', 'NetworkService',
     'OrderService', 'PlacementService', 'PremiumRateService',
     'ProductService', 'ProductTemplateService', 'ProposalLineItemService',
     'ProposalService', 'PublisherQueryLanguageService', 'RateCardService',
     'ReconciliationOrderReportService', 'ReconciliationReportRowService',
     'ReconciliationReportService', 'ReportService', 'SharedAdUnitService',
     'SuggestedAdUnitService', 'TeamService', 'UserService',
     'UserTeamAssociationService', 'WorkflowRequestService'),
  'v201502'=
    c('ActivityGroupService', 'ActivityService', 'AdExclusionRuleService',
     'AdRuleService', 'AudienceSegmentService', 'BaseRateService',
     'CompanyService', 'ContactService', 'ContentBundleService',
     'ContentMetadataKeyHierarchyService', 'ContentService',
     'CreativeService', 'CreativeSetService', 'CreativeTemplateService',
     'CreativeWrapperService', 'CustomFieldService',
     'CustomTargetingService', 'ExchangeRateService', 'ForecastService',
     'InventoryService', 'LabelService',
     'LineItemCreativeAssociationService', 'LineItemService',
     'LineItemTemplateService', 'LiveStreamEventService', 'NetworkService',
     'OrderService', 'PackageService', 'PlacementService',
     'PremiumRateService', 'ProductService', 'ProductPackageService',
     'ProductPackageItemService', 'ProductTemplateService',
     'ProposalLineItemService', 'ProposalService',
     'PublisherQueryLanguageService', 'RateCardService',
     'ReconciliationOrderReportService', 'ReconciliationReportRowService',
     'ReconciliationReportService', 'ReportService', 'SharedAdUnitService',
     'SuggestedAdUnitService', 'TeamService', 'UserService',
     'UserTeamAssociationService', 'WorkflowRequestService'),
  'v201505'=
    c('ActivityGroupService', 'ActivityService', 'AdExclusionRuleService',
     'AdRuleService', 'AudienceSegmentService', 'BaseRateService',
     'CompanyService', 'ContactService', 'ContentBundleService',
     'ContentMetadataKeyHierarchyService', 'ContentService',
     'CreativeService', 'CreativeSetService', 'CreativeTemplateService',
     'CreativeWrapperService', 'CustomFieldService',
     'CustomTargetingService', 'ExchangeRateService', 'ForecastService',
     'InventoryService', 'LabelService',
     'LineItemCreativeAssociationService', 'LineItemService',
     'LineItemTemplateService', 'LiveStreamEventService', 'NetworkService',
     'OrderService', 'PackageService', 'PlacementService',
     'PremiumRateService', 'ProductService', 'ProductPackageService',
     'ProductPackageItemService', 'ProductTemplateService',
     'ProposalLineItemService', 'ProposalService',
     'PublisherQueryLanguageService', 'RateCardService',
     'ReconciliationOrderReportService', 'ReconciliationReportRowService',
     'ReconciliationReportService', 'ReportService', 'SharedAdUnitService',
     'SuggestedAdUnitService', 'TeamService', 'UserService',
     'UserTeamAssociationService', 'WorkflowRequestService'),
  'v201508'=
    c('ActivityGroupService', 'ActivityService', 'AdExclusionRuleService',
     'AdRuleService', 'AudienceSegmentService', 'BaseRateService',
     'CompanyService', 'ContactService', 'ContentBundleService',
     'ContentMetadataKeyHierarchyService', 'ContentService',
     'CreativeService', 'CreativeSetService', 'CreativeTemplateService',
     'CreativeWrapperService', 'CustomFieldService',
     'CustomTargetingService', 'ExchangeRateService', 'ForecastService',
     'InventoryService', 'LabelService',
     'LineItemCreativeAssociationService', 'LineItemService',
     'LineItemTemplateService', 'LiveStreamEventService', 'NetworkService',
     'OrderService', 'PackageService', 'PlacementService',
     'PremiumRateService', 'ProductService', 'ProductPackageService',
     'ProductPackageItemService', 'ProductTemplateService',
     'ProposalLineItemService', 'ProposalService',
     'PublisherQueryLanguageService', 'RateCardService',
     'ReconciliationOrderReportService', 'ReconciliationReportRowService',
     'ReconciliationLineItemReportService',
     'ReconciliationReportService', 'ReportService', 'SharedAdUnitService',
     'SuggestedAdUnitService', 'TeamService', 'UserService',
     'UserTeamAssociationService', 'WorkflowRequestService')
)
